import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { useState } from 'react';
import { X, Loader } from 'lucide-react';
export default function KycDetailModal({ kyc, onClose, onApprove, onReject, isApprovePending, isRejectPending, }) {
    const [rejectReason, setRejectReason] = useState('');
    const [showRejectForm, setShowRejectForm] = useState(false);
    const handleReject = () => {
        if (rejectReason.trim().length >= 10) {
            onReject(rejectReason);
        }
    };
    return (_jsx("div", { className: "fixed inset-0 bg-black/50 flex items-center justify-center z-50", children: _jsxs("div", { className: "bg-white rounded-lg shadow-xl max-w-2xl w-full max-h-[90vh]\n        overflow-y-auto", children: [_jsxs("div", { className: "sticky top-0 flex items-center justify-between p-6\n          border-b border-gray-200 bg-white", children: [_jsxs("h2", { className: "text-xl font-semibold text-gray-900", children: ["KYC Details - ", kyc.shop_name] }), _jsx("button", { onClick: onClose, className: "p-1 hover:bg-gray-100 rounded-md", children: _jsx(X, { size: 24, className: "text-gray-600" }) })] }), _jsxs("div", { className: "p-6 space-y-6", children: [_jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-sm font-medium text-gray-500", children: "Shop Name" }), _jsx("p", { className: "text-lg font-medium text-gray-900", children: kyc.shop_name })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-sm font-medium text-gray-500", children: "Owner Name" }), _jsx("p", { className: "text-lg font-medium text-gray-900", children: kyc.owner_name })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-sm font-medium text-gray-500", children: "Phone" }), _jsx("p", { className: "text-lg font-medium text-gray-900", children: kyc.owner_phone })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-sm font-medium text-gray-500", children: "Status" }), _jsx("span", { className: `inline-flex px-3 py-1 rounded-full
                text-sm font-semibold ${kyc.status === 'pending'
                                                ? 'bg-yellow-100 text-yellow-800'
                                                : kyc.status === 'approved'
                                                    ? 'bg-green-100 text-green-800'
                                                    : 'bg-red-100 text-red-800'}`, children: kyc.status })] })] }), _jsxs("div", { className: "border-t border-gray-200 pt-6", children: [_jsx("h3", { className: "font-semibold text-gray-900 mb-4", children: "Documents" }), _jsxs("div", { className: "grid grid-cols-1 gap-4", children: [_jsx(DocumentViewer, { label: "Aadhaar", url: kyc.documents.aadhaar }), _jsx(DocumentViewer, { label: "GST Certificate", url: kyc.documents.gst }), _jsx(DocumentViewer, { label: "Shop Photo", url: kyc.documents.shop_photo })] })] }), kyc.rejection_reason && (_jsxs("div", { className: "bg-red-50 border border-red-200 rounded-lg p-4", children: [_jsx("h3", { className: "font-medium text-red-900", children: "Rejection Reason" }), _jsx("p", { className: "text-sm text-red-700 mt-1", children: kyc.rejection_reason })] })), kyc.status === 'pending' && (_jsx("div", { className: "border-t border-gray-200 pt-6 space-y-4", children: !showRejectForm ? (_jsxs("div", { className: "flex gap-3", children: [_jsxs("button", { onClick: onApprove, disabled: isApprovePending, className: "flex-1 bg-green-600 hover:bg-green-700\n                      disabled:bg-gray-400 text-white font-medium py-2\n                      rounded-md transition-colors flex items-center\n                      justify-center gap-2", children: [isApprovePending && (_jsx(Loader, { size: 20, className: "animate-spin" })), "Approve KYC"] }), _jsx("button", { onClick: () => setShowRejectForm(true), className: "flex-1 bg-red-600 hover:bg-red-700 text-white\n                      font-medium py-2 rounded-md transition-colors", children: "Reject KYC" })] })) : (_jsxs("div", { className: "space-y-4 bg-gray-50 p-4 rounded-lg", children: [_jsx("textarea", { value: rejectReason, onChange: (e) => setRejectReason(e.target.value), placeholder: "Enter rejection reason (min 10 characters)", maxLength: 500, className: "w-full px-4 py-2 border border-gray-300\n                      rounded-md focus:outline-none focus:ring-2\n                      focus:ring-red-500 h-24 resize-none" }), _jsxs("p", { className: "text-xs text-gray-500", children: [rejectReason.length, "/500 characters"] }), _jsxs("div", { className: "flex gap-3", children: [_jsx("button", { onClick: () => {
                                                    setShowRejectForm(false);
                                                    setRejectReason('');
                                                }, className: "flex-1 bg-gray-300 hover:bg-gray-400\n                        text-gray-900 font-medium py-2 rounded-md\n                        transition-colors", children: "Cancel" }), _jsxs("button", { onClick: handleReject, disabled: isRejectPending ||
                                                    rejectReason.trim().length < 10, className: "flex-1 bg-red-600 hover:bg-red-700\n                        disabled:bg-gray-400 text-white font-medium py-2\n                        rounded-md transition-colors flex items-center\n                        justify-center gap-2", children: [isRejectPending && (_jsx(Loader, { size: 20, className: "animate-spin" })), "Submit Rejection"] })] })] })) }))] })] }) }));
}
function DocumentViewer({ label, url }) {
    return (_jsxs("div", { className: "border border-gray-200 rounded-lg p-4", children: [_jsx("h4", { className: "font-medium text-gray-900 mb-2", children: label }), url ? (_jsx("a", { href: url, target: "_blank", rel: "noopener noreferrer", className: "text-blue-600 hover:text-blue-700 text-sm underline", children: "View Document" })) : (_jsx("p", { className: "text-sm text-gray-500", children: "Not provided" }))] }));
}
//# sourceMappingURL=KycDetailModal.js.map