import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { Lock, Unlock, Loader } from 'lucide-react';
export default function ShopTable({ data, pagination, onPageChange, onSuspend, onReinstate, isSuspendPending, isReinstatePending, }) {
    const [suspendShopId, setSuspendShopId] = useState(null);
    const [suspendReason, setSuspendReason] = useState('');
    const handleSuspend = (id) => {
        if (suspendReason.trim().length >= 10) {
            onSuspend(id, suspendReason);
            setSuspendShopId(null);
            setSuspendReason('');
        }
    };
    return (_jsxs(_Fragment, { children: [_jsx("div", { className: "bg-white rounded-lg shadow overflow-hidden", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { className: "bg-gray-50 border-b border-gray-200", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3 text-left text-xs font-medium\n                text-gray-700 uppercase tracking-wider", children: "Shop Name" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium\n                text-gray-700 uppercase tracking-wider", children: "Owner" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium\n                text-gray-700 uppercase tracking-wider", children: "KYC Status" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium\n                text-gray-700 uppercase tracking-wider", children: "Trust Score" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium\n                text-gray-700 uppercase tracking-wider", children: "Status" }), _jsx("th", { className: "px-6 py-3 text-right text-xs font-medium\n                text-gray-700 uppercase tracking-wider", children: "Actions" })] }) }), _jsx("tbody", { className: "divide-y divide-gray-200", children: data.map((shop) => (_jsxs("tr", { className: "hover:bg-gray-50", children: [_jsx("td", { className: "px-6 py-4 text-sm font-medium text-gray-900", children: shop.name }), _jsxs("td", { className: "px-6 py-4 text-sm text-gray-600", children: [shop.owner_name, _jsx("br", {}), _jsx("span", { className: "text-xs text-gray-500", children: shop.owner_phone })] }), _jsx("td", { className: "px-6 py-4 text-sm", children: _jsx("span", { className: `inline-flex px-2 py-1 rounded-full
                    text-xs font-semibold ${shop.kyc_status === 'approved'
                                                ? 'bg-green-100 text-green-800'
                                                : shop.kyc_status === 'pending'
                                                    ? 'bg-yellow-100 text-yellow-800'
                                                    : 'bg-red-100 text-red-800'}`, children: shop.kyc_status }) }), _jsx("td", { className: "px-6 py-4 text-sm text-gray-900", children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-16 bg-gray-200 rounded-full h-2", children: _jsx("div", { className: "h-2 bg-blue-600 rounded-full", style: { width: `${shop.trust_score}%` } }) }), _jsx("span", { className: "text-xs font-medium", children: shop.trust_score })] }) }), _jsx("td", { className: "px-6 py-4 text-sm", children: _jsx("span", { className: `inline-flex px-2 py-1 rounded-full
                    text-xs font-semibold ${shop.is_open
                                                ? 'bg-green-100 text-green-800'
                                                : 'bg-red-100 text-red-800'}`, children: shop.is_open ? 'Open' : 'Closed' }) }), _jsx("td", { className: "px-6 py-4 text-right text-sm space-x-2", children: shop.is_open ? (_jsxs("button", { onClick: () => setSuspendShopId(shop.id), disabled: isSuspendPending, className: "inline-flex items-center gap-1 px-3 py-1\n                        bg-red-100 text-red-700 rounded hover:bg-red-200\n                        disabled:opacity-50 transition-colors", children: [_jsx(Lock, { size: 16 }), "Suspend"] })) : (_jsxs("button", { onClick: () => onReinstate(shop.id), disabled: isReinstatePending, className: "inline-flex items-center gap-1 px-3 py-1\n                        bg-green-100 text-green-700 rounded\n                        hover:bg-green-200 disabled:opacity-50\n                        transition-colors", children: [_jsx(Unlock, { size: 16 }), "Reinstate"] })) })] }, shop.id))) })] }) }), _jsxs("div", { className: "flex items-center justify-between mt-6", children: [_jsxs("p", { className: "text-sm text-gray-600", children: ["Showing ", data.length, " of ", pagination.total, " results"] }), _jsxs("div", { className: "flex gap-2", children: [_jsx("button", { onClick: () => onPageChange(pagination.page - 1), disabled: pagination.page === 1, className: "px-4 py-2 bg-white border border-gray-300 rounded-md\n              hover:bg-gray-50 disabled:opacity-50", children: "Previous" }), Array.from({ length: pagination.pages }, (_, i) => i + 1).map((p) => (_jsx("button", { onClick: () => onPageChange(p), className: `px-3 py-2 rounded-md ${pagination.page === p
                                    ? 'bg-blue-600 text-white'
                                    : 'bg-white border border-gray-300 hover:bg-gray-50'}`, children: p }, p))), _jsx("button", { onClick: () => onPageChange(pagination.page + 1), disabled: pagination.page === pagination.pages, className: "px-4 py-2 bg-white border border-gray-300 rounded-md\n              hover:bg-gray-50 disabled:opacity-50", children: "Next" })] })] }), suspendShopId && (_jsx("div", { className: "fixed inset-0 bg-black/50 flex items-center\n          justify-center z-50", children: _jsxs("div", { className: "bg-white rounded-lg shadow-xl p-6 max-w-md", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-4", children: "Suspend Shop" }), _jsx("textarea", { value: suspendReason, onChange: (e) => setSuspendReason(e.target.value), placeholder: "Enter suspension reason (min 10 characters)", maxLength: 500, className: "w-full px-4 py-2 border border-gray-300 rounded-md\n                focus:outline-none focus:ring-2 focus:ring-red-500 h-24\n                resize-none mb-4" }), _jsxs("p", { className: "text-xs text-gray-500 mb-4", children: [suspendReason.length, "/500 characters"] }), _jsxs("div", { className: "flex gap-3", children: [_jsx("button", { onClick: () => {
                                        setSuspendShopId(null);
                                        setSuspendReason('');
                                    }, className: "flex-1 bg-gray-300 hover:bg-gray-400 text-gray-900\n                  font-medium py-2 rounded-md transition-colors", children: "Cancel" }), _jsxs("button", { onClick: () => handleSuspend(suspendShopId), disabled: isSuspendPending ||
                                        suspendReason.trim().length < 10, className: "flex-1 bg-red-600 hover:bg-red-700 disabled:bg-gray-400\n                  text-white font-medium py-2 rounded-md transition-colors\n                  flex items-center justify-center gap-2", children: [isSuspendPending && (_jsx(Loader, { size: 20, className: "animate-spin" })), "Suspend"] })] })] }) }))] }));
}
//# sourceMappingURL=ShopTable.js.map