// Mock data — Hyderabad/Bengaluru context, rupees, real-feel names.

const NEARBY_CATEGORIES = [
  { id: "all",     label: "All",       icon: "◉" },
  { id: "kirana",  label: "Kirana",    icon: "🛒" },
  { id: "veg",     label: "Veggies",   icon: "🥬" },
  { id: "pharma",  label: "Pharmacy",  icon: "💊" },
  { id: "food",    label: "Tiffin",    icon: "🍱" },
  { id: "pets",    label: "Pets",      icon: "🐾" },
  { id: "mobile",  label: "Mobile",    icon: "📱" },
];

const NEARBY_SHOPS = [
  {
    id: "kumars",
    name: "Kumar's Kirana",
    tagline: "Rice, dals, daily needs",
    owner: "Rajesh Kumar",
    since: 1994,
    category: "kirana",
    categoryLabel: "Kirana",
    rating: 4.8,
    reviews: 2145,
    trustScore: 98,
    verified: true,
    distance: 0.9,
    eta: "18–24 min",
    minOrder: 99,
    isOpen: true,
    closesAt: "10:00 PM",
    area: "Basheerbagh",
    cover: "#F4A62A",
    hue: 28,
    productCount: 412,
  },
  {
    id: "sri-lakshmi",
    name: "Sri Lakshmi Vegetables",
    tagline: "Farm-fresh, twice daily",
    owner: "Lakshmi Devi",
    since: 2008,
    category: "veg",
    categoryLabel: "Vegetables",
    rating: 4.6,
    reviews: 1189,
    trustScore: 94,
    verified: true,
    distance: 1.4,
    eta: "22–28 min",
    minOrder: 49,
    isOpen: true,
    closesAt: "9:30 PM",
    area: "Kukatpally",
    cover: "#6FA870",
    hue: 120,
    productCount: 138,
  },
  {
    id: "healthfirst",
    name: "HealthFirst Pharmacy",
    tagline: "Licensed · 24×7 delivery",
    owner: "Dr. Nithya Rao",
    since: 2016,
    category: "pharma",
    categoryLabel: "Pharmacy",
    rating: 4.9,
    reviews: 864,
    trustScore: 99,
    verified: true,
    distance: 2.1,
    eta: "25–35 min",
    minOrder: 0,
    isOpen: true,
    closesAt: "Open 24×7",
    area: "Madhapur",
    cover: "#E35D56",
    hue: 4,
    productCount: 2210,
  },
  {
    id: "amma-tiffin",
    name: "Amma's Tiffin Centre",
    tagline: "Home-style meals, daily",
    owner: "Suneetha Reddy",
    since: 2011,
    category: "food",
    categoryLabel: "Food & Tiffin",
    rating: 4.7,
    reviews: 3402,
    trustScore: 96,
    verified: true,
    distance: 1.7,
    eta: "20–25 min",
    minOrder: 80,
    isOpen: false,
    closesAt: "Opens 4:00 PM",
    area: "Jubilee Hills",
    cover: "#D3682A",
    hue: 22,
    productCount: 42,
  },
  {
    id: "raju-pet",
    name: "Raju Pet Supplies",
    tagline: "Food, toys, all breeds",
    owner: "Raju M.",
    since: 2019,
    category: "pets",
    categoryLabel: "Pets",
    rating: 4.5,
    reviews: 287,
    trustScore: 88,
    verified: true,
    distance: 2.8,
    eta: "28–35 min",
    minOrder: 149,
    isOpen: true,
    closesAt: "9:00 PM",
    area: "Gachibowli",
    cover: "#8957B2",
    hue: 285,
    productCount: 188,
  },
];

// Keyed by shop id
const NEARBY_PRODUCTS = {
  "kumars": [
    { section: "Staples",  items: [
      { id: "p1",  name: "Sona Masoori Rice", unit: "5 kg",  price: 385, stock: 24, hue: 38,  crumb: "Sri Lalitha" },
      { id: "p2",  name: "Toor Dal",          unit: "1 kg",  price: 165, stock: 48, hue: 48,  crumb: "Tata Sampann" },
      { id: "p3",  name: "Sunflower Oil",     unit: "1 L",   price: 148, stock: 60, hue: 52,  crumb: "Fortune" },
      { id: "p4",  name: "Whole Wheat Atta",  unit: "5 kg",  price: 245, stock: 18, hue: 30,  crumb: "Aashirvaad" },
    ]},
    { section: "Dairy & Bakery", items: [
      { id: "p5",  name: "Milk — Full Cream", unit: "500 ml", price: 33, stock: 3,  hue: 210, crumb: "Heritage" },
      { id: "p6",  name: "Paneer",            unit: "200 g",  price: 95, stock: 8,  hue: 40,  crumb: "Amul" },
      { id: "p7",  name: "Brown Bread",       unit: "400 g",  price: 55, stock: 0,  hue: 24,  crumb: "Modern" },
      { id: "p8",  name: "Eggs (brown)",      unit: "6 pc",   price: 78, stock: 14, hue: 28,  crumb: "Farm" },
    ]},
    { section: "Snacks", items: [
      { id: "p9",  name: "Haldiram Bhujia",   unit: "200 g",  price: 58, stock: 21, hue: 18, crumb: "Haldiram" },
      { id: "p10", name: "Parle-G Gold",      unit: "100 g",  price: 10, stock: 90, hue: 42, crumb: "Parle" },
      { id: "p11", name: "Good Day Butter",   unit: "100 g",  price: 35, stock: 33, hue: 46, crumb: "Britannia" },
      { id: "p12", name: "Lay's Classic",     unit: "52 g",   price: 20, stock: 72, hue: 54, crumb: "Lay's" },
    ]},
  ],
  "sri-lakshmi": [
    { section: "Fresh today", items: [
      { id: "v1", name: "Tomato",       unit: "1 kg",   price: 42, stock: 40, hue: 4,   crumb: "Picked 6am" },
      { id: "v2", name: "Onion",        unit: "1 kg",   price: 38, stock: 60, hue: 300, crumb: "Kurnool" },
      { id: "v3", name: "Green Chilli", unit: "250 g",  price: 18, stock: 24, hue: 110, crumb: "Fresh" },
      { id: "v4", name: "Coriander",    unit: "1 bunch",price: 12, stock: 22, hue: 110, crumb: "Morning cut" },
    ]},
  ],
  "healthfirst": [
    { section: "OTC", items: [
      { id: "m1", name: "Crocin 650", unit: "10 tabs", price: 42, stock: 50, hue: 340, crumb: "GSK" },
      { id: "m2", name: "Dolo 650",   unit: "15 tabs", price: 38, stock: 80, hue: 0,   crumb: "Micro" },
      { id: "m3", name: "ORS Packets",unit: "5 pc",    price: 110, stock: 36, hue: 200,crumb: "FDA" },
      { id: "m4", name: "Dettol Liquid",unit: "250 ml",price: 138, stock: 12, hue: 180,crumb: "Reckitt" },
    ]},
  ],
  "amma-tiffin": [
    { section: "Today's thalis", items: [
      { id: "t1", name: "Andhra Veg Meals",  unit: "full plate", price: 149, stock: 20, hue: 24, crumb: "Unlimited" },
      { id: "t2", name: "Ragi Mudda Meals",  unit: "full plate", price: 179, stock: 12, hue: 28, crumb: "Speciality" },
    ]},
  ],
  "raju-pet": [
    { section: "Dog food", items: [
      { id: "d1", name: "Pedigree Chicken", unit: "3 kg", price: 685, stock: 8, hue: 28, crumb: "Adult" },
    ]},
  ],
};

// Order timeline templates
const NEARBY_TIMELINE = [
  { key: "placed",   label: "Order placed",          blurb: "Your order was sent to the shop." },
  { key: "accepted", label: "Shop accepted",         blurb: "Rajesh accepted. Preparing now." },
  { key: "packed",   label: "Packed & ready",        blurb: "Waiting for partner pickup." },
  { key: "picked",   label: "Partner picked up",     blurb: "On the way to you." },
  { key: "delivered",label: "Delivered",             blurb: "Thanks for shopping local." },
];

Object.assign(window, { NEARBY_CATEGORIES, NEARBY_SHOPS, NEARBY_PRODUCTS, NEARBY_TIMELINE });
