/**
 * Error codes
 */

export const ERROR_CODES = {
  // Auth
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_LOCKED: 'OTP_LOCKED',
  OTP_REQUEST_FAILED: 'OTP_REQUEST_FAILED',
  INVALID_PHONE: 'INVALID_PHONE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  
  // Registration
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  KYC_SUBMIT_FAILED: 'KYC_SUBMIT_FAILED',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
  KYC_NOT_APPROVED: 'KYC_NOT_APPROVED',
  
  // Partner
  PARTNER_NOT_FOUND: 'PARTNER_NOT_FOUND',
  TOGGLE_FAILED: 'TOGGLE_FAILED',
  RATE_LIMITED: 'RATE_LIMITED',
  
  // Network
  NETWORK_ERROR: 'NETWORK_ERROR',
  OFFLINE: 'OFFLINE',
};
